title: cheat codes docs
description: hi plz describe me kthxbai
baseurl: /cheat-codes-docs
url: https://dndrks.github.io/cheat-codes-docs
permalink: pretty
sort_by: year, month
markdown: kramdown
kramdown:
  parse_block_html: true
plugins:
  - jekyll-feed
include: ['_pages']
collections_dir: collections
collections:
  - changelog